export { LOGIN_START, LOGIN_SUCCESS, LOGIN_FAILURE, login } from './login'
export { FETCH_DATA_START, FETCH_DATA_SUCCESS, FETCH_DATA_FAILURE, getData } from './getData'
export { REGISTER_START, REGISTER_SUCCESS, REGISTER_FAILURE} from './register'